version: "3"

services:

  db:
    build:
      context: ./db
    container_name: note_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5434:5432


  web:
    build:
      context: ./web
    container_name: note_web
    volumes:
      - ./web/www/package.json:/var/www/package.json
      - ./web/www/node_modules:/var/www/node_modules
      - ./web/www/vue.config.js:/var/www/vue.config.js
      - ./web/www/public/index.html:/var/www/public/index.html
      - ./web/www/src:/var/www/src
    ports:
      - "8082:8080"
#    networks:
#      - backend    

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: estate_nginx
  #   ports:
  #     - '8081:8081'
  #   volumes:
  #     - ./rest:/var/www/rest
  #     - ./nginx/rest.conf:/etc/nginx/conf.d/rest.conf:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/log:/var/log/nginx:consistent
  #   depends_on:
  #     - db
  #     - php