version: "3"

services:

  gateway:
    image: devopsfaith/krakend:1.4.1
    container_name: note_gateway
    environment:
      FC_ENABLE: 1
      FC_SETTINGS: settings
      # FC_PARTIALS: partials
      FC_TEMPLATES: templates
      FC_OUT: compiled.json
    volumes:
      - ./gateway:/etc/krakend
    ports:
      - 8080:8080

  web:
    build:
      context: ./web
    container_name: note_web
    volumes:
      - ./web/www/package.json:/var/www/package.json
      - ./web/www/node_modules:/var/www/node_modules
      - ./web/www/vue.config.js:/var/www/vue.config.js
      - ./web/www/public/index.html:/var/www/public/index.html
      - ./web/www/src:/var/www/src
    ports:
      - 8082:8080

  db:
    build:
      context: ./db
    container_name: note_core_db
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: note
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5434:5432    

  auth:
    image: quay.io/keycloak/keycloak:14.0.0
    container_name: note_auth
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: note_auth_db
      DB_DATABASE: auth
      DB_USER: postgres
      DB_SCHEMA: public
      DB_PASSWORD: postgres
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      # KEYCLOAK_LOGLEVEL: TRACE
      # ROOT_LOGLEVEL: TRACE
        # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
        #JDBC_PARAMS: "ssl=true"
    ports:
      - 9000:8080
    depends_on:
      - db.auth

  db.auth:
    build:
      context: ./db.auth
    container_name: note_auth_db
    volumes:
      - ./db.auth/data:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      POSTGRES_DB: auth
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres



# networks:
#   kong-net:
#     external: false



# http://localhost:9000/auth/realms/note/protocol/openid-connect/auth?response_type=code&client_id=login&redirect_uri=http://localhost:9000/auth/realms/note/account
#    networks:
#      - backend    

  # nginx:
  #   build:
  #     context: ./nginx
  #   container_name: estate_nginx
  #   ports:
  #     - '8081:8081'
  #   volumes:
  #     - ./rest:/var/www/rest
  #     - ./nginx/rest.conf:/etc/nginx/conf.d/rest.conf:ro
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/log:/var/log/nginx:consistent
  #   depends_on:
  #     - db
  #     - php