POST http://localhost:8081/v1/book
Authorization: Basic dTE6MTIz
Content-Type: application/json
Accept: application/json

{
  "name": "asdasda"
}

###

GET http://localhost:9090/v1/book
Authorization: Bearer alOGq0cBMTR8e6ILdJ9P7iI4lLW2KS0EDjSyw9C48Mq3GapbFskHcUMtx
Content-Type: application/json


###

GET http://localhost:9090/v1/bookmark/13
Authorization: Bearer 8PisxkkZcIHiZQR5tCmnn5uBBvppYwNFzw4vBZT0VwxfYILVenLEailaC
Content-Type: application/json

###

POST http://localhost:8081/v1/bookmark
Authorization: Basic dTE6MTIz
Content-Type: application/json
Accept: application/json

{
  "name": "asdasdxxa",
  "bookId": "17",
  "tags": ["aaa","1","kkkk"]
}

###

GET http://localhost:9090/v1/search/live?bookId=8
Authorization: Bearer 8PisxkkZcIHiZQR5tCmnn5uBBvppYwNFzw4vBZT0VwxfYILVenLEailaC


