POST http://localhost:9000/v1/registration
Content-Type: application/json
Accept: application/json

{
  "email": "test@test.com",
  "password": "test"
}

###

POST http://localhost:9000/v1/auth
Content-Type: application/json
Accept: application/json

{
  "email": "test@test.com",
  "password": "test"
}

###

POST http://localhost:9000/v1/auth/refresh?refresh_token=eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE2MjU3Njg2MjgsImlhdCI6MTYyNDkwNDYyOCwianRpIjoiOTdlZmExNDQtYmU0ZC00NDljLWEwYmMtMTgwYmU0NjQ1NTUzIn0.h-sP2roTKuh481YGXB5-W7iJO2M5JGUJv8BLuzSmxFE
Content-Type: application/json
Accept: application/json
